name: "Terraform Plan"

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Run Terraform Plan"
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.TF_VAR_ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TF_VAR_ARM_TENANT_ID }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Terraform
        run: |
          curl -o tf.zip https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
          unzip tf.zip
          sudo mv terraform /usr/local/bin/
          terraform version

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Run TFLint
        id: tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install.sh | bash
          tflint

      - name: Run Checkov
        id: checkov
        run: |
          pip install checkov
          checkov -d .

      - name: Run tfsec
        id: tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install.sh | bash
          tfsec .

      - name: Terraform Plan
        id: plan
        run: terraform plan
